package com.wzfuji.db.entity;

// Generated May 9, 2012 3:14:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Iteminfo generated by hbm2java
 */
@Entity
@Table(name = "iteminfo", catalog = "movierecommendationsystem")
public class Iteminfo implements java.io.Serializable {

	private int movieid;
	private String movietitle;
	private Integer releasedate;
	private Date videoreleasedate;
	private String imdbUrl;
	private Integer unknown;
	private Integer action;
	private Integer adventure;
	private Integer animation;
	private Integer childrenS;
	private Integer comedy;
	private Integer crime;
	private Integer documentary;
	private Integer drama;
	private Integer fantasy;
	private Integer filmNoir;
	private Integer horror;
	private Integer musical;
	private Integer mystery;
	private Integer romance;
	private Integer sciFi;
	private Integer thriller;
	private Integer war;
	private Integer western;

	public Iteminfo() {
	}

	public Iteminfo(int movieid) {
		this.movieid = movieid;
	}

	public Iteminfo(int movieid, String movietitle, Integer releasedate,
			Date videoreleasedate, String imdbUrl, Integer unknown,
			Integer action, Integer adventure, Integer animation,
			Integer childrenS, Integer comedy, Integer crime,
			Integer documentary, Integer drama, Integer fantasy,
			Integer filmNoir, Integer horror, Integer musical, Integer mystery,
			Integer romance, Integer sciFi, Integer thriller, Integer war,
			Integer western) {
		this.movieid = movieid;
		this.movietitle = movietitle;
		this.releasedate = releasedate;
		this.videoreleasedate = videoreleasedate;
		this.imdbUrl = imdbUrl;
		this.unknown = unknown;
		this.action = action;
		this.adventure = adventure;
		this.animation = animation;
		this.childrenS = childrenS;
		this.comedy = comedy;
		this.crime = crime;
		this.documentary = documentary;
		this.drama = drama;
		this.fantasy = fantasy;
		this.filmNoir = filmNoir;
		this.horror = horror;
		this.musical = musical;
		this.mystery = mystery;
		this.romance = romance;
		this.sciFi = sciFi;
		this.thriller = thriller;
		this.war = war;
		this.western = western;
	}

	@Id
	@Column(name = "movieid", unique = true, nullable = false)
	public int getMovieid() {
		return this.movieid;
	}

	public void setMovieid(int movieid) {
		this.movieid = movieid;
	}

	@Column(name = "movietitle", length = 20)
	public String getMovietitle() {
		return this.movietitle;
	}

	public void setMovietitle(String movietitle) {
		this.movietitle = movietitle;
	}

	@Column(name = "releasedate")
	public Integer getReleasedate() {
		return this.releasedate;
	}

	public void setReleasedate(Integer releasedate) {
		this.releasedate = releasedate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "videoreleasedate", length = 10)
	public Date getVideoreleasedate() {
		return this.videoreleasedate;
	}

	public void setVideoreleasedate(Date videoreleasedate) {
		this.videoreleasedate = videoreleasedate;
	}

	@Column(name = "IMDbURL", length = 200)
	public String getImdbUrl() {
		return this.imdbUrl;
	}

	public void setImdbUrl(String imdbUrl) {
		this.imdbUrl = imdbUrl;
	}

	@Column(name = "unknown")
	public Integer getUnknown() {
		return this.unknown;
	}

	public void setUnknown(Integer unknown) {
		this.unknown = unknown;
	}

	@Column(name = "Action")
	public Integer getAction() {
		return this.action;
	}

	public void setAction(Integer action) {
		this.action = action;
	}

	@Column(name = "Adventure")
	public Integer getAdventure() {
		return this.adventure;
	}

	public void setAdventure(Integer adventure) {
		this.adventure = adventure;
	}

	@Column(name = "Animation")
	public Integer getAnimation() {
		return this.animation;
	}

	public void setAnimation(Integer animation) {
		this.animation = animation;
	}

	@Column(name = "Children_s")
	public Integer getChildrenS() {
		return this.childrenS;
	}

	public void setChildrenS(Integer childrenS) {
		this.childrenS = childrenS;
	}

	@Column(name = "Comedy")
	public Integer getComedy() {
		return this.comedy;
	}

	public void setComedy(Integer comedy) {
		this.comedy = comedy;
	}

	@Column(name = "Crime")
	public Integer getCrime() {
		return this.crime;
	}

	public void setCrime(Integer crime) {
		this.crime = crime;
	}

	@Column(name = "Documentary")
	public Integer getDocumentary() {
		return this.documentary;
	}

	public void setDocumentary(Integer documentary) {
		this.documentary = documentary;
	}

	@Column(name = "Drama")
	public Integer getDrama() {
		return this.drama;
	}

	public void setDrama(Integer drama) {
		this.drama = drama;
	}

	@Column(name = "Fantasy")
	public Integer getFantasy() {
		return this.fantasy;
	}

	public void setFantasy(Integer fantasy) {
		this.fantasy = fantasy;
	}

	@Column(name = "Film_Noir")
	public Integer getFilmNoir() {
		return this.filmNoir;
	}

	public void setFilmNoir(Integer filmNoir) {
		this.filmNoir = filmNoir;
	}

	@Column(name = "Horror")
	public Integer getHorror() {
		return this.horror;
	}

	public void setHorror(Integer horror) {
		this.horror = horror;
	}

	@Column(name = "Musical")
	public Integer getMusical() {
		return this.musical;
	}

	public void setMusical(Integer musical) {
		this.musical = musical;
	}

	@Column(name = "Mystery")
	public Integer getMystery() {
		return this.mystery;
	}

	public void setMystery(Integer mystery) {
		this.mystery = mystery;
	}

	@Column(name = "Romance")
	public Integer getRomance() {
		return this.romance;
	}

	public void setRomance(Integer romance) {
		this.romance = romance;
	}

	@Column(name = "Sci_Fi")
	public Integer getSciFi() {
		return this.sciFi;
	}

	public void setSciFi(Integer sciFi) {
		this.sciFi = sciFi;
	}

	@Column(name = "Thriller")
	public Integer getThriller() {
		return this.thriller;
	}

	public void setThriller(Integer thriller) {
		this.thriller = thriller;
	}

	@Column(name = "War")
	public Integer getWar() {
		return this.war;
	}

	public void setWar(Integer war) {
		this.war = war;
	}

	@Column(name = "Western")
	public Integer getWestern() {
		return this.western;
	}

	public void setWestern(Integer western) {
		this.western = western;
	}

}
