package com.wzfuji.db.entity;

// Generated May 9, 2012 3:14:09 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ItemCluster generated by hbm2java
 */
@Entity
@Table(name = "ItemCluster", catalog = "movierecommendationsystem")
public class ItemCluster implements java.io.Serializable {

	private ItemClusterId id;
	private int clusterId;

	public ItemCluster() {
	}

	public ItemCluster(ItemClusterId id, int clusterId) {
		this.id = id;
		this.clusterId = clusterId;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "userId", nullable = false)),
			@AttributeOverride(name = "itemId", column = @Column(name = "itemId", nullable = false)) })
	public ItemClusterId getId() {
		return this.id;
	}

	public void setId(ItemClusterId id) {
		this.id = id;
	}

	@Column(name = "clusterId", nullable = false)
	public int getClusterId() {
		return this.clusterId;
	}

	public void setClusterId(int clusterId) {
		this.clusterId = clusterId;
	}

}
