package com.wzfuji.db.entity;

// Generated May 9, 2012 3:14:09 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RatingId generated by hbm2java
 */
@Embeddable
public class RatingId implements java.io.Serializable {

	private int userid;
	private int itemid;

	public RatingId() {
	}

	public RatingId(int userid, int itemid) {
		this.userid = userid;
		this.itemid = itemid;
	}

	@Column(name = "userid", nullable = false)
	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	@Column(name = "itemid", nullable = false)
	public int getItemid() {
		return this.itemid;
	}

	public void setItemid(int itemid) {
		this.itemid = itemid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RatingId))
			return false;
		RatingId castOther = (RatingId) other;

		return (this.getUserid() == castOther.getUserid())
				&& (this.getItemid() == castOther.getItemid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserid();
		result = 37 * result + this.getItemid();
		return result;
	}

}
