package com.wzfuji.db.entity;

// Generated May 9, 2012 3:14:09 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Userinfo generated by hbm2java
 */
@Entity
@Table(name = "userinfo", catalog = "movierecommendationsystem")
public class Userinfo implements java.io.Serializable {

	private int userid;
	private Integer age;
	private String gender;
	private String occupation;
	private String zipcode;

	public Userinfo() {
	}

	public Userinfo(int userid) {
		this.userid = userid;
	}

	public Userinfo(int userid, Integer age, String gender, String occupation,
			String zipcode) {
		this.userid = userid;
		this.age = age;
		this.gender = gender;
		this.occupation = occupation;
		this.zipcode = zipcode;
	}

	@Id
	@Column(name = "userid", unique = true, nullable = false)
	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "gender", length = 2)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "occupation", length = 20)
	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	@Column(name = "zipcode", length = 10)
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

}
