package com.wzfuji.db.entity;

// Generated May 9, 2012 3:14:09 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AverageUserRating generated by hbm2java
 */
@Entity
@Table(name = "AverageUserRating", catalog = "movierecommendationsystem")
public class AverageUserRating implements java.io.Serializable {

	private int userid;
	private Double averagerating;

	public AverageUserRating() {
	}

	public AverageUserRating(int userid) {
		this.userid = userid;
	}

	public AverageUserRating(int userid, Double averagerating) {
		this.userid = userid;
		this.averagerating = averagerating;
	}

	@Id
	@Column(name = "userid", unique = true, nullable = false)
	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	@Column(name = "averagerating", precision = 22, scale = 0)
	public Double getAveragerating() {
		return this.averagerating;
	}

	public void setAveragerating(Double averagerating) {
		this.averagerating = averagerating;
	}

}
