package com.wzfuji.db.entity;

// Generated May 9, 2012 3:14:09 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Info generated by hbm2java
 */
@Entity
@Table(name = "info", catalog = "movierecommendationsystem")
public class Info implements java.io.Serializable {

	private String name;
	private Integer value;

	public Info() {
	}

	public Info(String name) {
		this.name = name;
	}

	public Info(String name, Integer value) {
		this.name = name;
		this.value = value;
	}

	@Id
	@Column(name = "name", unique = true, nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value")
	public Integer getValue() {
		return this.value;
	}

	public void setValue(Integer value) {
		this.value = value;
	}

}
