package com.wzfuji.db.entity;

// Generated May 9, 2012 3:14:09 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Occupation generated by hbm2java
 */
@Entity
@Table(name = "occupation", catalog = "movierecommendationsystem")
public class Occupation implements java.io.Serializable {

	private String name;

	public Occupation() {
	}

	public Occupation(String name) {
		this.name = name;
	}

	@Id
	@Column(name = "name", unique = true, nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
