package com.wzfuji.db.entity;

// Generated May 9, 2012 3:14:09 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Rating generated by hbm2java
 */
@Entity
@Table(name = "rating", catalog = "movierecommendationsystem")
public class Rating implements java.io.Serializable {

	private RatingId id;
	private Double rating;

	public Rating() {
	}

	public Rating(RatingId id) {
		this.id = id;
	}

	public Rating(RatingId id, Double rating) {
		this.id = id;
		this.rating = rating;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userid", column = @Column(name = "userid", nullable = false)),
			@AttributeOverride(name = "itemid", column = @Column(name = "itemid", nullable = false)) })
	public RatingId getId() {
		return this.id;
	}

	public void setId(RatingId id) {
		this.id = id;
	}

	@Column(name = "rating", precision = 22, scale = 0)
	public Double getRating() {
		return this.rating;
	}

	public void setRating(Double rating) {
		this.rating = rating;
	}

}
